#!/bin/sh

# English and hebrew keyboards
setxkbmap -option grp:switch,grp:alt_shift_toggle,grp_led:scroll us,il

# feh set background
~/dotfiles/.config/scripts/startup-scripts/.fehbg

# picom
picom -b

# Keybinfings
xbindkeys --file ~/dotfiles/.config/xbindkeys/config

# Xresources
xrdb -load ~/dotfiles/.config/X11/Xresources

# In case there is another monitor
~/dotfiles/.config/scripts/startup-scripts/.xrandr-second-monitor
